### ISSUE TITLE
Add Docker Compose for Casandra

### ISSUE THREAD

**Issue by kishorekommula** [opensource-util-library/docker-compose-utilities#16]

**Comment by rmidhun23** [comment]
Hi @kishorekommula I would like to take this up, if this is not being actively worked on already.

**Comment by mallikarjungunda** [comment]
@rmidhun23 please proceed and add PR.

**Comment by rmidhun23** [comment]
@mallikarjungunda, Please review and thank you for assigning the PR to me !

**Comment by mallikarjungunda** [comment]
Thank you for the PR, you are welcome to add more utilities to the repo.

Appreciate for your contribution to the repo.

Thanks
Mallik
